name: Install Swift on Ubuntu
inputs:
  swift_release_tag:
    required: true
    type: string
  ubuntu_version:
    type: string
    default: "22.04"

outputs:
  install_directory:
    description: The install directory.
    value: ${{ steps.install_swift.outputs.install_directory }}
  ld_library_directory:
    description: The directory that contains the shared libraries.
    value: ${{ steps.install_swift.outputs.ld_library_directory }}

runs:
  using: composite
  steps:
    - name: Install Swift Ubuntu
      id: install_swift
      shell: bash
      env:
        SWIFT_RELEASE_TAG: ${{ inputs.swift_release_tag }}
        UBUNTU_VERSION: ${{ inputs.ubuntu_version }}
      run: |
        # Variables
        distro_dirname="ubuntu${UBUNTU_VERSION/[.]/}"
        install_dirname="${SWIFT_RELEASE_TAG}-ubuntu${UBUNTU_VERSION}"
        install_directory="${HOME}/${install_dirname}"
        ld_library_directory="${install_directory}/usr/lib/swift/linux"
        archive_filename="${install_dirname}.tar.gz"
        lowercase_swift_release_tag="$( echo "${SWIFT_RELEASE_TAG}" | tr '[:upper:]' '[:lower:]')"
        archive_url="https://download.swift.org/${lowercase_swift_release_tag}/${distro_dirname}/${SWIFT_RELEASE_TAG}/${archive_filename}"

        # Download and expand the release archive
        wget "${archive_url}"
        tar --strip-components 1 -xvzf "${archive_filename}" -C /
        # Update LD_LIBRARY_PATH
        echo "LD_LIBRARY_PATH=${ld_library_directory}:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"
        # Output the install directory
        echo "install_directory=${install_directory}" >> $GITHUB_OUTPUT
        # Output the value that should be added to the LD_LIBRARY_PATH env variable.
        echo "ld_library_directory=${ld_library_directory}" >> $GITHUB_OUTPUT

      # run: |
      #   # Variables
      #   distro_dirname="ubuntu${UBUNTU_VERSION/[.]/}"
      #   install_dirname="${SWIFT_RELEASE_TAG}-ubuntu${UBUNTU_VERSION}"
      #   install_directory="${HOME}/${install_dirname}"
      #   ld_library_directory="${install_directory}/usr/lib/swift/linux"
      #   archive_filename="${install_dirname}.tar.gz"
      #   lowercase_swift_release_tag="$( echo "${SWIFT_RELEASE_TAG}" | tr '[:upper:]' '[:lower:]')"
      #   archive_url="https://download.swift.org/${lowercase_swift_release_tag}/${distro_dirname}/${SWIFT_RELEASE_TAG}/${archive_filename}"
      #   # Download and expand the release archive
      #   wget "${archive_url}"
      #   tar -xvzf "${archive_filename}" -C "${HOME}"
      #   # Add the usr/bin Swift install directory to the PATH for later actions
      #   echo "${install_directory}/usr/bin" >> "${GITHUB_PATH}"
      #   # Update LD_LIBRARY_PATH
      #   echo "LD_LIBRARY_PATH=${ld_library_directory}:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"
      #   # Output the install directory
      #   echo "install_directory=${install_directory}" >> $GITHUB_OUTPUT
      #   # Output the value that should be added to the LD_LIBRARY_PATH env variable.
      #   echo "ld_library_directory=${ld_library_directory}" >> $GITHUB_OUTPUT
