name: CI for PR Merge

on:
  pull_request:
    branches: [ main ]

jobs:
  ubuntu_build:
    runs-on: ubuntu-24.04
    env:
      CC: clang
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: ./
        name: Install Swift
        id: install_swift
        with:
          swift_release_tag: "swift-6.0.2-RELEASE"
          ubuntu_version: "22.04"
      - name: Verify Installation
        shell: bash
        env:
          LD_LIBRARY_DIRECTORY: ${{ steps.install_swift.outputs.ld_library_directory }}
        run: |
          # Verify version is correct
          swift --version | grep "Swift version 6.0.2"
          # Verify the LD_LIBRARY_DIRECTORY output is correct.
          [[ "${LD_LIBRARY_DIRECTORY}" == "/usr/lib/swift/linux" ]] || \
            (echo >&2 "Unexpected install directory. ${LD_LIBRARY_DIRECTORY}" && exit 1)
          # Verify that LD_LIBRARY_PATH has been updated
          [[ "${LD_LIBRARY_PATH}" =~ "${LD_LIBRARY_DIRECTORY}" ]] || \
            (echo >&2 "Did not find LD_LIBRARY_DIRECTORY in LD_LIBRARY_PATH. ${LD_LIBRARY_PATH}" && exit 1)

