name: CI for PR Merge

on:
  pull_request:
    branches: [ main ]

jobs:
  ubuntu_build:
    runs-on: ubuntu-22.04
    env:
      CC: clang
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: ./
        name: Install Swift
        id: install_swift
        with:
          swift_release_tag: "swift-5.8-RELEASE"
          ubuntu_version: "22.04"
      - name: Verify Installation
        shell: bash
        env:
          INSTALL_DIRECTORY: ${{ steps.install_swift.outputs.install_directory }}
          LD_LIBRARY_DIRECTORY: ${{ steps.install_swift.outputs.ld_library_directory }}
        run: |
          [[ "${INSTALL_DIRECTORY}" == "${HOME}/swift-5.8-RELEASE-ubuntu22.04" ]] || \
            (echo >&2 "Unexpected install directory. ${INSTALL_DIRECTORY}" && exit 1)
          [[ "${LD_LIBRARY_DIRECTORY}" == "${INSTALL_DIRECTORY}/usr/lib/swift/linux" ]] || \
            (echo >&2 "Unexpected install directory. ${LD_LIBRARY_DIRECTORY}" && exit 1)
          # Verify that installed version is found in PATH
          swift_path="$(which swift)"
          [[ "${swift_path}" =~ "${INSTALL_DIRECTORY}" ]] || \
            (echo >&2 "Unexpected swift path. ${swift_path}" && exit 1)
          # Verify that LD_LIBRARY_PATH has been updated
          [[ "${LD_LIBRARY_PATH}" =~ "${LD_LIBRARY_DIRECTORY}" ]] || \
            (echo >&2 "Did not find LD_LIBRARY_DIRECTORY in LD_LIBRARY_PATH. ${LD_LIBRARY_PATH}" && exit 1)

